# TODO: Delete this workflow.
name: Build Website - Text (Test)
on:
  push:
    branches:
      - sc-72674-add-slug-field-to-metadata

jobs:
  build:
    uses: ./.github/workflows/build-branch.yml
    with:
      branch: ${{ github.ref }}
      num_workers: 1
      enable_python_cache: false
      enable_sphinx_cache: true
      enable_qml_execution_times_cache: false
      skip_execution_of_examples: true
      skip_execution_times_aggregation: true
      skip_sphinx_build_file_aggregation: false
      sphinx_build_output_format: text

  upload-dev:
    needs:
      - build
    uses: ./.github/workflows/upload-text.yml
    with:
      branch: ${{ github.ref }}

    secrets:
      aws_region: ${{ secrets.AWS_REGION }}
      aws_access_key_id: ${{ secrets.DEV_GLASS_ONION_AWS_ACCESS_KEY_ID }}
      aws_secret_access_key: ${{ secrets.DEV_GLASS_ONION_AWS_SECRET_ACCESS_KEY }}
      aws_text_s3_bucket_id: ${{ secrets.DEV_GLASS_ONION_DEMOS_BUCKET_ID }}
